"""
tor_chutney.py  –  Real Tor demo using chutney (fully offline / air-gapped)

Requires (all must be installed on the VM):
    apt install tor chutney tshark  (or wireshark-common for tshark)
    pip install stem requests[socks]

Chutney is expected at one of the standard locations:
    /usr/share/doc/chutney   (Debian/Ubuntu package)
    /usr/share/chutney
    ~/chutney                (manual git clone)
    $CHUTNEY_PATH            (env var override)

Usage from topology.py:
    from tor_chutney import TorChutneyDemo
    demo = TorChutneyDemo(capture=True)
    demo.start()          # brings up the chutney network
    demo.run_request()    # sends an HTTP request over Tor to the local server
    demo.stop()           # tears everything down cleanly
"""

import os
import shutil
import signal
import socket
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path


# ---------------------------------------------------------------------------
# Chutney discovery
# ---------------------------------------------------------------------------

_CHUTNEY_CANDIDATES = [
    os.environ.get("CHUTNEY_PATH", ""),
    "/usr/share/doc/chutney",
    "/usr/share/chutney",
    str(Path.home() / "chutney"),
    "/opt/chutney",
]


def _find_chutney() -> Path:
    """Return the first chutney root that contains tools/bootstrap-network.sh."""
    for candidate in _CHUTNEY_CANDIDATES:
        if not candidate:
            continue
        p = Path(candidate)
        if (p / "tools" / "bootstrap-network.sh").exists():
            return p
    raise FileNotFoundError(
        "Could not find chutney. Set $CHUTNEY_PATH or install with:\n"
        "  sudo apt install chutney\n"
        "  # or: git clone https://gitlab.torproject.org/tpo/core/chutney.git ~/chutney"
    )


# ---------------------------------------------------------------------------
# Network topology written as a chutney network file
# ---------------------------------------------------------------------------

# A minimal offline network: 1 directory authority + 3 relays + 1 client.
# All ports are on loopback so there is no external traffic at all.
# The hidden-service target is our local HTTP server (passed at runtime).
_NETWORK_TEMPLATE = """\
# Auto-generated by tor_chutney.py – do not edit by hand.

# ---- directory authority ------------------------------------------------
{da_section}

# ---- relays -------------------------------------------------------------
{relay_section}

# ---- client -------------------------------------------------------------
{client_section}
"""

_DA_TEMPLATE = """\
<node>
  <name>DA</name>
  <DirServer>1</DirServer>
  <AuthoritativeDirectory>1</AuthoritativeDirectory>
  <V3AuthoritativeDirectory>1</V3AuthoritativeDirectory>
  <ServerTransportPlugin></ServerTransportPlugin>
  <OrPort>{or_port}</OrPort>
  <DirPort>{dir_port}</DirPort>
  <Address>127.0.0.1</Address>
  <SocksPort>0</SocksPort>
</node>
"""

_RELAY_TEMPLATE = """\
<node>
  <name>{name}</name>
  <OrPort>{or_port}</OrPort>
  <DirPort>{dir_port}</DirPort>
  <Address>127.0.0.1</Address>
  <SocksPort>0</SocksPort>
</node>
"""

_CLIENT_TEMPLATE = """\
<node>
  <name>Client</name>
  <SocksPort>{socks_port}</SocksPort>
  <OrPort>0</OrPort>
  <DirPort>0</DirPort>
  <Address>127.0.0.1</Address>
</node>
"""


# ---------------------------------------------------------------------------
# Helper: wait for a TCP port to be open
# ---------------------------------------------------------------------------

def _wait_for_port(host: str, port: int, timeout: float = 60.0, interval: float = 1.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((host, port), timeout=2):
                return True
        except OSError:
            time.sleep(interval)
    return False


# ---------------------------------------------------------------------------
# Helper: stream subprocess output with a prefix label
# ---------------------------------------------------------------------------

def _stream(name: str, proc: subprocess.Popen) -> threading.Thread:
    def _run():
        for raw in proc.stdout:
            try:
                line = raw.decode("utf-8", errors="replace").rstrip()
            except Exception:
                line = repr(raw)
            print(f"[{name}] {line}", flush=True)

    t = threading.Thread(target=_run, daemon=True)
    t.start()
    return t


# ---------------------------------------------------------------------------
# Main demo class
# ---------------------------------------------------------------------------

class TorChutneyDemo:
    """
    Orchestrates a fully local chutney Tor network and optionally captures
    traffic on the loopback interface so students can inspect real Tor cells
    in Wireshark and contrast them with the toy-XOR onion demo.

    Parameters
    ----------
    server_ip   : IP of the HTTP server running inside Mininet (default 10.0.0.7)
    server_port : Port of the HTTP server (default 8080)
    socks_port  : Local SOCKS5 port the Tor client will expose (default 19050)
    capture     : If True, start tshark on loopback before the request
    capture_dir : Directory to write .pcap files (default ./captures/)
    """

    # Port allocations – all on loopback, nothing touches the real network
    _DA_OR_PORT  = 17001
    _DA_DIR_PORT = 17002
    _RELAY_PORTS = [
        (17011, 17012),  # relay0: or_port, dir_port
        (17021, 17022),  # relay1
        (17031, 17032),  # relay2
    ]
    _DEFAULT_SOCKS_PORT = 19050

    def __init__(
        self,
        server_ip: str = "10.0.0.7",
        server_port: int = 8080,
        socks_port: int = _DEFAULT_SOCKS_PORT,
        capture: bool = False,
        capture_dir: Path | None = None,
    ):
        self.server_ip   = server_ip
        self.server_port = server_port
        self.socks_port  = socks_port
        self.capture     = capture

        self._chutney_root: Path | None = None
        self._net_dir: tempfile.TemporaryDirectory | None = None
        self._chutney_proc: subprocess.Popen | None = None
        self._tshark_proc: subprocess.Popen | None = None
        self._capture_file: Path | None = None
        self._stream_threads: list[threading.Thread] = []

        base = Path(__file__).resolve().parent
        self._capture_dir = capture_dir or (base / "captures")
        self._capture_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Bootstrap the chutney Tor network and wait until it is ready."""
        print("[tor] Locating chutney …")
        self._chutney_root = _find_chutney()
        print(f"[tor] Using chutney at {self._chutney_root}")

        self._net_dir = tempfile.mkdtemp(prefix="tor_chutney_")
        net_path = Path(self._net_dir)

        # Write the network description file that chutney will consume
        net_file = net_path / "network.conf"
        self._write_network_file(net_file)

        # Bootstrap: creates key material, torrc files, starts all Tor processes
        print("[tor] Bootstrapping chutney network (this takes ~30 s) …")
        env = os.environ.copy()
        env["CHUTNEY_NETWORK"] = str(net_file)
        env["CHUTNEY_DATA_DIR"] = str(net_path / "nodes")

        bootstrap = self._chutney_root / "tools" / "bootstrap-network.sh"
        self._chutney_proc = subprocess.Popen(
            ["bash", str(bootstrap)],
            cwd=str(self._chutney_root),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        t = _stream("chutney", self._chutney_proc)
        self._stream_threads.append(t)
        self._chutney_proc.wait()

        if self._chutney_proc.returncode not in (0, None):
            raise RuntimeError(
                f"chutney bootstrap-network.sh exited with code {self._chutney_proc.returncode}"
            )

        # Wait for the client's SOCKS port to be ready – this is the reliable
        # signal that the network has reached consensus and is usable.
        print(f"[tor] Waiting for SOCKS port 127.0.0.1:{self.socks_port} …")
        ready = _wait_for_port("127.0.0.1", self.socks_port, timeout=120)
        if not ready:
            raise TimeoutError(
                f"Tor client SOCKS port {self.socks_port} did not open within 120 s. "
                "Check that Tor is installed and the chutney nodes started correctly."
            )

        # Give the network a few more seconds to build circuits
        print("[tor] SOCKS port open – waiting 10 s for circuits to build …")
        time.sleep(10)
        print("[tor] Chutney network ready.")

        # Optionally start a tshark capture on loopback
        if self.capture:
            self._start_tshark()

    def run_request(self, path: str = "/") -> str:
        """
        Send an HTTP GET request through the Tor SOCKS5 proxy to the
        Mininet HTTP server and return the response body.

        The Mininet server is reached directly by IP (server_ip:server_port);
        the exit node forwards the plain HTTP request to it, so Wireshark on
        the Mininet links will show cleartext HTTP while the loopback capture
        shows encrypted Tor cells – exactly the teaching contrast we want.
        """
        try:
            import requests  # type: ignore
        except ImportError:
            raise ImportError(
                "The 'requests' library is required for tor_chutney.run_request().\n"
                "Install it with: pip install requests[socks]"
            )

        url = f"http://{self.server_ip}:{self.server_port}{path}"
        proxies = {
            "http":  f"socks5h://127.0.0.1:{self.socks_port}",
            "https": f"socks5h://127.0.0.1:{self.socks_port}",
        }

        print(f"[tor] Sending request via Tor SOCKS5 proxy → {url}")
        try:
            resp = requests.get(url, proxies=proxies, timeout=30)
            body = resp.text
            print(f"[tor] Response: HTTP {resp.status_code}, {len(body)} bytes")
            print("[tor] First 512 bytes of response:")
            print(body[:512])
            return body
        except Exception as exc:
            print(f"[tor] Request failed: {exc}", file=sys.stderr)
            raise

    def stop(self) -> None:
        """Tear down the chutney network and stop any captures."""
        print("[tor] Stopping chutney network …")

        # Stop tshark first so the pcap is flushed before we say where it is
        if self._tshark_proc:
            try:
                self._tshark_proc.send_signal(signal.SIGINT)
                self._tshark_proc.wait(timeout=5)
            except Exception:
                self._tshark_proc.terminate()
            finally:
                self._tshark_proc = None
            if self._capture_file:
                print(f"[tor] Loopback capture saved to {self._capture_file}")

        # Use chutney's own stop script if available
        stop_script = self._chutney_root / "tools" / "stop-network.sh" if self._chutney_root else None
        if stop_script and stop_script.exists():
            env = os.environ.copy()
            if self._net_dir:
                env["CHUTNEY_DATA_DIR"] = str(Path(self._net_dir) / "nodes")
            subprocess.run(
                ["bash", str(stop_script)],
                cwd=str(self._chutney_root),
                env=env,
                timeout=15,
            )
        else:
            # Fallback: kill all Tor processes that used our temp node dir
            if self._net_dir:
                subprocess.run(
                    ["pkill", "-f", str(self._net_dir)],
                    capture_output=True,
                )

        # Clean up temp directory
        if self._net_dir:
            shutil.rmtree(self._net_dir, ignore_errors=True)
            self._net_dir = None

        print("[tor] Chutney network stopped.")

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _write_network_file(self, path: Path) -> None:
        """Generate a minimal chutney .conf that runs entirely on loopback."""
        da_section = _DA_TEMPLATE.format(
            or_port=self._DA_OR_PORT,
            dir_port=self._DA_DIR_PORT,
        )

        relay_sections = []
        for idx, (or_port, dir_port) in enumerate(self._RELAY_PORTS):
            relay_sections.append(
                _RELAY_TEMPLATE.format(
                    name=f"Relay{idx}",
                    or_port=or_port,
                    dir_port=dir_port,
                )
            )

        client_section = _CLIENT_TEMPLATE.format(socks_port=self.socks_port)

        content = _NETWORK_TEMPLATE.format(
            da_section=da_section,
            relay_section="\n".join(relay_sections),
            client_section=client_section,
        )
        path.write_text(content)
        print(f"[tor] Wrote network config to {path}")

    def _start_tshark(self) -> None:
        """Start tshark on loopback, filtering only on our Tor ports."""
        tshark_bin = shutil.which("tshark")
        if not tshark_bin:
            print("[tor] WARNING: tshark not found, skipping loopback capture.", file=sys.stderr)
            return

        ports = [
            self._DA_OR_PORT, self._DA_DIR_PORT,
            *[p for pair in self._RELAY_PORTS for p in pair],
            self.socks_port,
        ]
        bpf = " or ".join(f"port {p}" for p in ports)

        self._capture_file = self._capture_dir / "tor_loopback.pcap"
        cmd = [
            tshark_bin,
            "-i", "lo",          # loopback interface
            "-f", bpf,           # BPF capture filter
            "-w", str(self._capture_file),
            "-q",
        ]
        print(f"[tor] Starting tshark on lo: {' '.join(cmd)}")
        self._tshark_proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        t = _stream("tshark", self._tshark_proc)
        self._stream_threads.append(t)
        time.sleep(1)   # give tshark a moment to start capturing
